
# data related
data_folder: "dataproxCheckSDF_s1_06"
cam_param: "dataproxCheckSDF_s1_06/cam.txt"
sdf_path: "dataproxCheckSDF_s1_06/vicon_sdf.pkl"
use_joints_conf: true
interpenetration: false
is_seq: false # solve a video sequence

# output related
# output_folder: 'output_Linear_hand_face'
result_folder: 'results'
visualize: False
interactive: True
save_meshes: true
save_images: true
# device
use_cuda: true

rho_contact: 5e-2
contact_angle: 45

# annotation related
#for annotation that contains 3D joint
use_3d: false 
#if the model is smpl, the hip is not for supervision
use_hip: false 
dataset: 'offline'
joints_to_ign:
    - 1
    - 9
    - 12
# model related
model_folder: 'models'
model_type: 'smplx' # smpl smpllsp
float_dtype: "float32"
gender: male # male female neutral
#use_hand: true
#use_face: true

#prior related
use_vposer: true
prior_folder: 'priors/vposerDecoderWeights.npz'
body_prior_type: 'l2'
left_hand_prior_type: 'l2'
right_hand_prior_type: 'l2'
jaw_prior_type: 'l2'
# expr_prior_type: 'l2'
num_pca_comps: 12

#weight related
data_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
body_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4e0
    - 4.78e0
    - 4.78e0
    - 4.78e0
    - 4.78e0
shape_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
coll_loss_weights:
    - 0.0
    - 0.0
    - 1000.0
    - 4500.0
    - 0.0
    - 0.0
    - 0.0
contact_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    # - 0.0
    - 1e4
foot_contact_loss_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 5e3
expr_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
    - 0.5e1
hand_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4
    - 4.78
    - 4.78
    - 4.78
    - 4.78
jaw_pose_prior_weights:
    # First phase
    - 4.04e03,4.04e04,4.04e04
    # Second phase
    - 4.04e03,4.04e04,4.04e04
    # Third phase
    - 574,5740,5740
    # Fourth phase
    - 47.8,478,478
    - 47.8,478,478
    - 47.8,478,478
    - 47.8,478,478
hand_joints_weights: 
    - 0.0
    - 0.0
    - 0.0
    - 0.1
    - 2.0
    - 2.0
    - 2.0
face_joints_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 2.0
    - 2.0
    - 2.0
sdf_penetration_weights:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 10.0
    - 5.0

# optimization related
rho: 100
optim_type: 'lbfgsls' #lbfgsls
ftol: 1e-9
gtol: 1e-9
lr: 1.0
# Max number of optimization iterations
maxiters: 30

# fixed parameter
fix_scale: true
scale: 1
fix_shape: false
shape:
    - 2.39806 
    - 0.678491
    - 1.38193 
    - -0.966748 
    - -1.29383 
    - -0.795755 
    - -0.303195 
    - -1.1032 
    - -0.197056 
    - -0.102728 
