
# data related
data_folder: "data"
cam_param: "data/3DOH50K_Parameters.txt"
use_joints_conf: true
interpenetration: false
is_seq: false # solve a video sequence

# output related
output_folder: 'output'
result_folder: 'results'
visualize: False
interactive: True
save_meshes: true
save_images: true
# device
use_cuda: true

# annotation related
#for annotation that contains 3D joint
use_3d: false 
#if the model is smpl, the hip is not for supervision
use_hip: true 
dataset: 'offline'

# model related
model_folder: 'models'
model_type: 'smpllsp' # smpl smpllsp
float_dtype: "float32"
gender: neutral # male female neutral

#prior related
use_vposer: true
prior_folder: 'priors'
body_prior_type: 'l2'

#weight related
data_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
body_pose_prior_weights:
    - 4.04e2
    - 4.04e2
    - 57.4e0
    - 4.78e0
shape_weights:
    - 1.0e2
    - 5.0e1
    - 1.0e1
    - 0.5e1
coll_loss_weights:
    - 0.0
    - 0.0
    - 0.01
    - 1.0

# optimization related
rho: 100
optim_type: 'lbfgsls' #lbfgsls
ftol: 1e-9
gtol: 1e-9
lr: 1.0
# Max number of optimization iterations
maxiters: 30

# fixed parameter
fix_scale: false
scale: 1000.
fix_shape: false
shape:
    - 2.39806 
    - 0.678491
    - 1.38193 
    - -0.966748 
    - -1.29383 
    - -0.795755 
    - -0.303195 
    - -1.1032 
    - -0.197056 
    - -0.102728 